# public/config.yml
backend:
  name: github
  repo: adrianciaff/blockport-xyz-website # *** REQUIRED: Replace with your repo path ***
  branch: main # Or the branch you want the CMS to commit to
  cms_label_prefix: decap-cms/ # Optional: Prefix for CMS-generated commit messages

media_folder: "public/uploads" # Location where uploaded media files will be stored
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

publish_mode: editorial_workflow # Enable draft/review/publish workflow

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # *** The folder where blog posts will be stored ***
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document, usually mapped to Markdown frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      # Title field is required by default for the slug
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: false }
      # Optional: Add fields for summary/excerpt, tags, featured image, etc.
      # - { label: "Summary", name: "summary", widget: "text", required: false }
      # - { label: "Tags", name: "tags", widget: "list", required: false }
      # - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }